apiVersion: v1
kind: Service
metadata:
  labels:
    app: consummer
  name: consummer
  namespace: default
  resourceVersion: "3105"
  uid: 93f60b71-fbe2-45b9-8b18-fa0e1cf1d334
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: consummer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
