apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-code
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/flach/projects/aws-sqs/consummer
  persistentVolumeReclaimPolicy: Retain