server:
  port: 8080

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIAX52TIWXLIIYIJBLP
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/545098610134/PatientIntegration